### ISSUE TITLE
No error thrown when routes folder is missing

### ISSUE THREAD

**Issue by jorbascrumps** [tests-always-included/restify-router-magic#1]
I've been trying to get this module to work for the last day or so but it doesn't seem to work correctly. The documentation states that an error will be thrown if the `routes/` folder cannot be found but that doesn't seem to be the case.

My current application structure is:

```
app/
|-- routes/
|---- index.js
|-- server.js
```

No routes are loaded and if I remove or rename the `routes/` folder no error is thrown.

**app/server.js:**

```
import restify from 'restify';
import routerMagic from 'restify-router-magic';

const server = restify.createServer();

routerMagic(server, null, (err) => {
    console.log(err); // null
});

server.listen(8080, () => {});
```

If I'm simply missing something, please let me know. Thanks!

**Comment by jorbascrumps** [comment]
As a workaround, I added a config object with `routesPath` defined. This seems to have resolved the route loading issue but the default behaviour is still confusing.

```
const routesConfig = {
    routesPath: path.join(__dirname, 'routes')
};
```

**Comment by fidian** [comment]
Looks like I can use `glob("anything/*.js")` and it just silently provides an empty array, saying no files match.  No error is produced.  I'm fixing this now.

**Comment by fidian** [comment]
All fixed.  Closed prematurely.  Opening again in the hopes you'll test the fix before I publish.

**Comment by jorbascrumps** [comment]
Thanks for looking into this so quickly, I really appreciate it!

I did a quick test and received an error, but not quite as expected. Given my sample application structure above, would you expect an error to be thrown? If I put the `routes/` folder on the same level as `app/` then routes are loaded correctly.

**Comment by fidian** [comment]
It's based on where you start the app - the process's current working directory.  Thus it would not be `app/routes/` unless you've configured it like this:

```
routesConfig = {
    routesPath: "app/routes/"
}
```

The reason your workaround works is because it's adding the dirname of the index file, not the current working directory.

**Comment by jorbascrumps** [comment]
Perfect, then you can close this and consider it resolved. Thanks!
