### ISSUE TITLE
Doesn't appear to support route versioning

### ISSUE THREAD

**Issue by jorbascrumps** [tests-always-included/restify-router-magic#2]
I could be wrong, but I'm not seeing any support for route versioning. Is this correct?

**Comment by fidian** [comment]
Could you elaborate on what you would expect to see?

I would envision you creating versioning in the directory structure.

```
routes/
    v1/
        index.js
    v2/
        index.js
```

**Comment by jorbascrumps** [comment]
restify supports [multiple versions on a single route](http://restify.com/#versioned-routes):

```
server.get({path: PATH, version: ['2.0.0', '2.1.0', '2.2.0']}, sendV2);
```

I suppose you could accomplish the same thing by having a route file export another version.

**routes/v1/index.js:**

```
export const get = (req, res, next) => {};
```

**routes/v2/index.js:**

```
import { get } from '../v1';

export get;
```

**Comment by fidian** [comment]
This doesn't fundamentally align with the principles of this project.

I'm happy to hear how you would implement these changes while keeping the current structure intact.

For the APIs that I'm usually using, we do not version or we would move most of the work off to another library, like some manager or service.

```
var manager = require("../lib/account-manager");
module.exports = {
    get: function (req, res, next) => {
        manager.doTheWork(req.x, req.y, next);
    }
};
```
