### ISSUE TITLE
Typescript Types?

### ISSUE THREAD

**Issue by joselevelsup** [tests-always-included/restify-router-magic#6]
Any chances making type declarations for this module. I am currently using this with Typescript and actually like this module.

**Comment by fidian** [comment]
Would you look at the `typescript` branch and see if I did it right? I'm mostly guessing because I don't use this module with TypeScript.

**Comment by joselevelsup** [comment]
Sure. I'll take a look at this when I can.

**Comment by joselevelsup** [comment]
So I checked out the branch and used it locally with a test project. The code looking like

```
import * as restify from "restify";
import * as restifyRouterMagic from "../restify-router-magic";
import * as path from "path";

const server: any = restify.createServer();

restifyRouterMagic(server, {
  routesPath: path.resolve(__dirname, "routes")
});

server.listen(8080, () => {
  console.log("server");
})

```

I imported the module locally and this error thrown was:
`error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("~/Documents/projects/restify-router-magic/index")' has no compatible call signatures.`

Now before I start blaming anyone, I'm gonna try and blame myself. Did I do anything wrong?

**Comment by fidian** [comment]
I'm not great at TypeScript, so I am unsure. It could very well have been me and how I created the definitions. I was hoping that you'd have some experience with the typings and would be able to diagnose problems with my initial pass.

**Comment by joselevelsup** [comment]
I'll take a deeper look and see what I can do. I don't have much experience with typings myself but it doesn't hurt to try 😄

**Comment by fidian** [comment]
I've got this working with TypeScript without errors. If you still see problems with 1.3.0 or later, let me know.
